-- ============================================
-- Maxfolio Database Schema Setup for Supabase
-- ============================================
-- Run this SQL in your Supabase SQL Editor to set up the database.
-- Dashboard > SQL Editor > New Query > Paste & Run

-- 1. Create Profiles Table (with audio_url and balance for new features)
CREATE TABLE IF NOT EXISTS profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    job TEXT,
    bio TEXT,
    skills TEXT,
    portfolio_url TEXT,
    audio_url TEXT,
    balance BIGINT DEFAULT 1000,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Accepted Jobs Table (for tracking job applications)
CREATE TABLE IF NOT EXISTS accepted_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT REFERENCES profiles(username) ON DELETE CASCADE,
    job_title TEXT,
    pay TEXT,
    accepted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_profiles_username ON profiles(username);
CREATE INDEX IF NOT EXISTS idx_profiles_created_at ON profiles(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_accepted_jobs_username ON accepted_jobs(username);

-- 4. If you already have the profiles table, run this to add new columns:
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS audio_url TEXT;
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS balance BIGINT DEFAULT 1000;

-- 5. Enable Row Level Security (optional but recommended)
-- Uncomment the lines below if you want to enable RLS
-- ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE accepted_jobs ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (since this is a fun, auth-free app)
-- CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
-- CREATE POLICY "Anyone can insert profiles" ON profiles FOR INSERT WITH CHECK (true);
-- CREATE POLICY "Public jobs are viewable by everyone" ON accepted_jobs FOR SELECT USING (true);
-- CREATE POLICY "Anyone can insert jobs" ON accepted_jobs FOR INSERT WITH CHECK (true);

-- ============================================
-- Quick Start:
-- 1. Create a Supabase project at https://supabase.com
-- 2. Go to SQL Editor and run this script
-- 3. Go to Project Settings > Database and copy your connection string
-- 4. Add DATABASE_URL to your Vercel environment variables
-- ============================================
