-- ============================================
-- Maxfolio Database Schema Setup for Supabase
-- ============================================
-- Run this SQL in your Supabase SQL Editor to set up the database.
-- Dashboard > SQL Editor > New Query > Paste & Run

-- 1. Create Profiles Table (main user data)
CREATE TABLE IF NOT EXISTS profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    job TEXT,
    bio TEXT,
    skills TEXT,
    portfolio_url TEXT,
    audio_url TEXT,
    balance BIGINT DEFAULT 1000,
    net_worth BIGINT DEFAULT 1000,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Accepted Jobs Table (jobs users have applied to)
CREATE TABLE IF NOT EXISTS accepted_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT REFERENCES profiles(username) ON DELETE CASCADE,
    job_title TEXT NOT NULL,
    company TEXT,
    pay TEXT,
    accepted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Relationships Table (matchmaker connections)
CREATE TABLE IF NOT EXISTS relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT REFERENCES profiles(username) ON DELETE CASCADE,
    partner_name TEXT NOT NULL,
    partner_species TEXT,
    relationship_type TEXT,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Songs Table (user compositions)
CREATE TABLE IF NOT EXISTS songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT REFERENCES profiles(username) ON DELETE CASCADE,
    song_name TEXT DEFAULT 'Untitled Composition',
    notes_data TEXT,
    duration_ms INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. If tables already exist, add new columns:
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS audio_url TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS balance BIGINT DEFAULT 1000;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS net_worth BIGINT DEFAULT 1000;

-- Add company column to accepted_jobs if missing
ALTER TABLE accepted_jobs ADD COLUMN IF NOT EXISTS company TEXT;

-- 6. Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_profiles_username ON profiles(username);
CREATE INDEX IF NOT EXISTS idx_profiles_created_at ON profiles(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_accepted_jobs_username ON accepted_jobs(username);
CREATE INDEX IF NOT EXISTS idx_relationships_username ON relationships(username);
CREATE INDEX IF NOT EXISTS idx_songs_username ON songs(username);

-- ============================================
-- After running this, make sure to also run the 
-- application and test creating a profile!
-- ============================================
